### ISSUE TITLE
3 March Data?

### ISSUE THREAD

**Issue by jflanaga** [chan0park/VoynaSlov#1]
Thanks a lot for making this available. I was wondering if something went wrong collecting the Twitter/public-reaction tweets on 3 March. There's only 1661 tweet ids. There's 456821 tweets IDS the day before and  272488 the day after. In fact, I don't any days have as low a count as on the 3 March.

**Comment by chan0park** [comment]
Hi! Thanks for the comment. There were a few dates where our server was down, and thus the data collection script was paused. I suggest excluding March 3rd from your analysis.
